### ISSUE TITLE
alert!!

### ISSUE THREAD

**Issue by samridhi18** [aniketdogra09/clashWithCovid#1]
Hi!! I just Checked the game..Its just awesome.but the alert for winning orfor game over comes twice

**Comment by aniketdogra09** [comment]
Thanks for writing. As per you, I've noted the issue and I'm working on a way to reform it. As of now, I need to take a clear analysis of the logic as the code for the same is simple as that it alerts only once. Your extension of any suggestion shall be greatly welcome.
Until that thanks for improving our experience.
